[system]
lattice = "graphene"
formation_shape = "triangle" # rectangle | triangle
formation = "armchair"
size_x = 2
size_y = 2
rotation_angle_deg = 0

# bond length (nm)
lattice_const = 0.142

[hamiltonian]
t1 = -2.8
t2 = -2.8
mu = 0.0 #1.89
gamma = 0.05
spin_on = false

[simulation]
use_strict_solver = false
dt = 0.01
t0 = 0.0
t_max = 3000.0
a_tol = 1e-16
r_tol = 1e-18

[field]
intensity = 1e13
mode = "time_impulse"       #time_impulse
phase = 0.0
omega = 4.75 # clean = 2.14, all = 2.28
t_shift = 1500.0
sigma_gaus = 100 #60.07
sigma_ddf = 0.01
B_ext = false


[analysis]
omega_cut_off = 48 # on res = 69
fourier_dt_fs = 0.005
run_sigma_ext = false  
run_dipole_acc = true 

[thermo]
T = 300

[features]
coulomb = true
coulomb_onsite_eV = 10.0 # Hubbard U (eV), 5-10 typical for graphene
self_consistent_phase = false  # enable: current -> A_ind -> phi_ind -> update hopping (induced phase loop)
zeeman_external = false  
zeeman_induced = false