[system]
lattice = "graphene"
formation_shape = "triangle" # rectangle | triangle
formation = "zigzag"
size_x = 5
size_y = 5
rotation_angle_deg = 0

# bond length (nm)
lattice_const = 0.14210

[hamiltonian]
t1 = -2.8
t2 = -2.8
mu = 0.0
gamma = 0.05
spin_on = false


[simulation]
use_strict_solver = false
dt = 0.01
t0 = 0.0
t_max = 2000.0
r_tol = 1e-14
a_tol = 1e-16

[field]
intensity = 1e13
mode = "time_impulse"       #time_impulse
phase = 0.0
omega = 2.10
t_shift = 1000.0
sigma_gaus = 100 #60.07
sigma_ddf = 0.01
B_ext = false

[analysis]
omega_cut_off = 25
fourier_dt_fs = 0.01 # for pretty 0.001 or 0.005. HHG
run_sigma_ext = false 
run_dipole_acc = true #true

[thermo]
T = 300
use_charge_doping = false        # if true, ignore mu for Rho_0
Q_doping = 8.0                    # total extra electrons relative to neutral

[features]
coulomb = true
coulomb_onsite_eV = 20.0 # Hubbard U (eV), 
self_consistent_phase = false  # enable: current -> A_ind -> phi_ind -> update hopping (induced phase loop)
zeeman_external = false
zeeman_induced = false   

